common:
  port: 8080 # порт, на котором будет запускаться наше приложение
postgres:
  database_url: postgresql://forum_user:forum_password@localhost:5433/forum
  require_ssl: false # стоит ли шифровать соединение с базой